Modified weighted random pick function
1bardesign/batteries pull request #42
Opened 2021-11-18 09:10 UTC by speakk

- Now accepts a table from which it will pick the random value from,
  instead of an index
- Changed function name to better reflect the way it now works

2021-11-18 22:24 UTC, 1bardesign requested changes
few tweaks then LGTM :pray:

2021-11-18 22:24 UTC, 1bardesign commented on tablex.lua
> +	return #w
should be tablex.back(t)

2021-11-18 22:24 UTC, 1bardesign commented on tablex.lua
> +function tablex.pick_weighted_random(w, t, r)
i think `t, w, r` is a better argument order; t is always the first argument in all these functions, the weights feel more like a parameter than the "subject"

2021-11-19 08:06 UTC, speakk commented
Good comments @1bardesign , implemented those.

2021-11-22 23:59 UTC, merged